### ISSUE TITLE
Not all lights/functions working

### ISSUE THREAD

**Issue by okayjeffrey** [koryk/dashing-philips-hue#1]
I keep receiving these and am not very skilled with ruby to fix. It appears that it doesn't recognize the math in some of the variables and is breaking on call.

127.0.0.1 - - [21/Mar/2016 20:53:33] "GET /events HTTP/1.1" 200 - 52.2204
dashing start
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
brightness is 200brightness is 200brightness is 200================================================================================
scheduler caught exception:
undefined method `*' for nil:NilClass
/Users/[user]/Development/dashboard/jobs/korhome.rb:35:in`block (2 levels) in <top (required)>'
/Users/[user]/Development/dashboard/jobs/korhome.rb:15:in `each'
/Users/[user]/Development/dashboard/jobs/korhome.rb:15:in`block in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in`trigger_block'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in`call'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

**Comment by okayjeffrey** [comment]
**I fixed some issues in the ERB file**
  $('li .widget-korhome .on').click(function() {
    var onInput = $(this).parent().parent().parent().parent().parent().children('input');
    var ID = onInput.val();
    var lightInfo = "{\"on\":true,\"bri\":254,\"sat\":254,\"hue\":15762}";

```
$.ajax({
    type: "PUT",
    url: "http://"+ipAddress+"/api/"+userId+"/lights/"+ID+"/state",
    dataType: "json",
    success: function(info) { console.log("WORKED", info); },
    error: function(info) { console.log("NOPE", info); },
    data: lightInfo
});
```

  });

**The issue above is still logging but app is now working and colors are changing. The ERB just was hard set.**
